title: "#WritingAWrong"
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
source: writingawrong
destination: _site
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  tylerlirette

# Build settings
markdown: kramdown
incremental: true

jekyll-minifier:
  exclude: '*'
  preserve_php: true
  compress_javascript: false